
* 怎样学好高数
  [日期：2006-10-24] 	来源：  作者： 	[字体：大 中 小]
  高数对于自学考试的人来说，十分之难。本人从事过多年高数自学考试教学工作，对此深有体会。很多参加自学考试的人都是业余学习，需要很强的毅力。自学考试大部分科目都是考前背一背就可以通过，但高数就完全不同了，它需要扎实的功底，需要很强的逻辑推理能力，需要做大量枯燥无味的习题，需要翻烂一本书的耐力，需要........所以很多自学考试的“勇士”往往是“栽”在高数这一门上，屡战屡败，盲然中他们付出了太多，失去了太多！我有个学生，高数考了不下十次，其它科目全过了，就等高数一门就可拿到学位了，好惨！

  　　其实高数并非想象的那么不可高攀，最关键的是要注意学习方法，而高数一和高数二的学习又有所不同，下面具体介绍我的对学习高数的技巧。

  　　一）高数一（或工专），首先要有扎实的基本功因为高数一主要是微积分，它实际是有关函数的各种运算。所以首先就是熟悉各种函数的性质、运算等，这些内容都是高中课本上的内容，在高数一书本上只是简单介绍而已。那么对那些准备学习高数一的朋友，要先看看你的基础如何，如果中学的知识全还给老师的话，我建议你先看看中学的书，特别是有关指数函数、幂函数、对数函数、三角函数等一定要很熟，否则要想学好高数可能就需要很多时间了。

  　　在有较扎实的基础后，现在可以开始学习高数了。因为高数一各章是相互关联层层推进的，每一章都是后一章的基础，所以学习时一定要按部就班，只有将这一章真正搞懂了才可进入下一章学习，切忌为求快而去速学，欲速则不达嘛，特别是当前面没学好硬去学后面的，会将不懂的问题越集越多，此时自学者的心态就会越来越烦躁，并且不知从何处下手去改善，所见的题目、知识全都不懂，这时很大部分朋友可能就会放弃做逃兵。所以一定要一章一章去学。

  　　在学每一章时，建议先将课本内容看一遍，如果一遍还不明的话，再看一遍。然后看书上的例题，同时试着去做书后的习题。有条件的话，可以买一些参考书来看和做题。做了部分题后，就拿一套以往考试题看看考题中本章有没有题，可以看看关于本章出题的方式。一定要多做题，高数一讲究“熟能生巧”，“熟做高数三千题，考试一定就能行）。

  　　高数一学习是一个长期的过程，所以往后学的过程中，一定要制定计划定期拿一些前面章节的题来做。很多考生在学习过程中，往往学到后面的就把前面内容忘记了。边学边忘肯定是不行的，也会影响到后面的学习。

  　　高数一历年来都是通过率较低的一门学科，原因在于学习着必须真正认真去学才能通过，仅仅靠蒙是很难过的。它出题千变万化，根本无法去估题。并且由于各章相互联系，所以根本无法区分重点和非重点，很多学友问可否划划重点，我的答案是没有重点，因为全是重点。另外强烈推荐学习者去参加一些培训或有一个可以请教的高手，这样可以在遇到难题时及时得到解决同时可以学到各种解题方法(一般书上的解题方法太少)。

  　　另外还要特别强调的是高数学习最好是一个连贯的过程，也就是说一定要制订一个阶段性的学习计划，比如用半年或一年的时间去学它。很多学高数屡战屡败的朋友可能都有这样的经历：准备考比如十月的高数，那么就去报班读，但读到一小半时可能由于种种原因就读不下去了，高数也只学到积分那章就放弃了，心里可能想，哎高数那么难，留到明年再考吧。借口一有，马上放弃十月的考试了。那等明年，这种情况可能又会重复一次，从而周而复始，于是所有科目都过了，只剩下高数这个硬骨头，心理自然就生出高数好难的念头。这种情况在我以前上课时经常发生，刚开课时，教室挤满人，但课程还没上到一半人就走掉一半了，最后能坚持下来的人寥寥无几，而最后能通过考试的恰好就是这些坚持下来的学生。所以有时我就学员当准备考高数时，最好只报考高数一门，全心投入去学习它，当你中途感到吃力坚持不下时，不要找任何借口逃脱，而要想想问题出在哪里，为什么学不下去？找到问题所在然后克服它，那最后一定能成功！

  　　二)高数二的学习与高数一相比有很大的差异。首先说一说它们之间的异同，第一点，高数二不需要太多的基础知识，只是概率里有一点积分和导数的简单计算；第二点，高数一整个内容由微分扣积分这条线贯穿始终，而高数二内容连贯性不是很强；第三点，高数一学习要从根本上加强对基本概念和理论的理解，拓宽解题思路，加强例题典型题的分析和综合练习，并能对典型题举一反三，所以需要做大量题，而高数二要加强基本概念的理解，并能掌握书本上的基本例题即可，不需举一反三，考试题目特别是概率的大题大多千篇一律，无非就是将书上例题数字改一改而已，所以不需做大量题，只需将书上题目“真正”会做即可，如果你能找到大量的题的话，你仔细看看，肯定是千篇一律的。

  　　根据以上几点，我们再来谈谈高数二的学习，首先学习过程中，一定要将每一章内容、概念、定理等真正理解，这可以通过多看几遍书来达到。看书时一定要静下心来，因为高数二内容较难理解，当看不下去时一定不要放弃，要硬着头皮往下读。这里要注意一点的是，高数二中可能会有很多对定理、推论的证明过程，这些证明过程又长又复杂，我建议大家对这些证明过程可以不用去看，你只需捉住精华---定理、推论，好好理解它们就可以了。

  　　当看懂一章内容之后，可以将书后的习题拿来做一做，一定要会做，而不是做完就了事。高数二主要的题型无非就是：（1）行列式的计算；（2）矩阵的运算；（3）线性方程组的求解；（4）特征值和特征向量的计算；（5）二次型的化简；（6）概率论中求概率；（7）求分布与求数字特征；（8）数理统计中求点估计，求区间估计与求检验的拒绝域。书上关于这几方面的题目一定要做完并理解怎样做的。

  　　总得说来，高数一内容好象少点，也不难理解，但由于变化多端，且相互联系紧密，故出题多样，且一道题可能涉及到好几章内容，所以更难点。而高数二，内容较多，也很难理解，但出题简单，题目比较单一，并且有可能都见过。对它们的学习，很精辟的一句话：高数一，多做题；高数二，多看书理解！

  　　以上观点为本人学习和教学中的理解，仅供大家参考。对于广大自考者，学习高数一定要结合自己的知识背景和学习特点总结出自己学习高数的方法和技巧。我相信：天道酬勤，主要付出一份辛苦，一定会有一份收获的！努力吧！



* 题记―――高等数学，是某些自考专业的重要课程。
  但对于如何通过考试，如何学好这门课程，许多朋友都是百展莫愁，头痛不已。而高数及格率又是所有科目中及格率最低的几门之一，成为许多考生能否顺利完成专业课程的主要障碍。

  数学，是一门深奥而又有趣的课程。如果增加对这门课程的自信心，不要畏惧它，你会很容易接受这门课，你也会发觉其实这门课程并不难，这对于学好数学是一个非常必要的条件。



  培根说，“数学是科学的大门和钥匙。”的确，数学是科学技术的基础。高等数学与应用数学（包括线性代数、概率论与数理统计、复变函数、数学物理方程，等等）是各专业的重要基础理论课。在会计专业里，比如财务成本管理，审计，评估，管理会计，……等等科目里都有高等数学的影子；在经济学领域里，更是如此。无论微观经济还是宏观经济的经典理论里都有高等数学的烙印。大凡经济学大家们，数学功底都极深。比如，约翰·纳什，萨缪尔逊，中国的茅于轼，……都是数学家或者有相当深厚的数学功底。即使是有些敌视数理经济学的张五常，也免不了要创造一个“张式数学”（这是俺给的名字）来加强论文说服力和逻辑性。

  数学学科的特点是高度的抽象理论与严密的逻辑推理，要通过学习数学提高抽象思维能力，逻辑推理能力，数学运算能力以及应用数学解决实际问题的能力。任何一门数学课的内容都是由基本概念(定义)、基本理论(性质与定理)、基本运算(计算)及应用四部分组成，要学好数学就要在这四个部分上认真钻研刻苦努力，多下功夫。

  基本概念要清楚，要读懂，要理解透彻、叙述准确，不能似是而非、一知半解。数学的推理完全靠基本概念，基本概念不清楚，很多内容就学不懂，无法掌握和运用。例如，线性代数中向量组的线性相关性、线性无关性，向量组的秩与极大无关组，矩阵的相似对角形等，初学者往往掌握不深不透，这就要通过复习与作习题的过程中逐步深入、反复思考、彻底读懂。

  基本理论是数学推理论证的核心，是由一些概念、性质与定理组成的，有些定理并不要求每位初学者都会证明，但定理的条件和结论一定要清楚，要熟悉定理并学会使用定理，有些内容是必须牢记的。例如，矩阵的初等变换是线性代数的重要内容之一。求逆方阵、求矩阵的秩，解线性方程组等都离不开矩阵的初等变换，要懂得其中的道理，为什么可以用初等变换解决以上问题，理论依据是什么？是作初等行变换还是列变换。又如，线性方程组解的存在定理及解的结构定理，判断向量组线性相关与线性无关的有关定理，都是必须牢记的。在概率论的学习中，微积分知识对于理解概率统计的理论很重要。

  掌握数学概念和理论并学会运用主要靠作题，在读懂了内容后要作题，而且要作一定数量的题，才能不断加深对内容的理解，提高解题能力，熟才能生巧，捷径是没有的，“不作题等于没学数学”这是大家公认的事实。在解题过程中要不断总结思路和方法，掌握解题规律性，通过作题提高分析问题、解决问题的能力，也就是逐步提高数学素养。我大学时期的数学老师是北大的研究生（当时正准备去美国读数学博士），福建省当年高考的状元，他高考数学是120分（满分），物理99分，……他告诉我学习微积分的经验就是作四万道题，保证微积分通过（包括考研微积分部分）。——作题的重要性可见一般。

  要学好数学就要认真对待学习的各个环节。首先是听课，听课要精神集中，如能预习效果会更好，要抓住教师讲课中对问题的分析，作好笔记，学会自己动手，边听边记，特别要记下没有听懂的部分。第二个环节是复习整理笔记及作题，课下结合教材和笔记进行复习，要对笔记进行整理按自己的思路，整理出这一次课的内容。在复习好并掌握了内容后再作习题，切忌边翻书边看例题，照猫画虎式地完成练习册上的习题，这样做是收不到任何效果的。要用作题来检验自己的学习，是真懂了还是没完全懂。对于没有彻底读懂的地方再反复思考，直到完全读懂。（当然，我不鼓励象我一样，自己一个人看书，最好找一下免费的视频课件，效率会高些）

  接着是阶段总结。每学完一章，自己要作总结。总结包括一章中的基本概念，核心内容；本章解决了什么问题，是怎样解决的；依靠哪些重要理论和结论，解决问题的思路是什么？理出条理，归纳出要点与核心内容以及自己对问题的理解和体会。

  最后是全课程的总结。在考试前要作总结，这个总结将全书内容加以整理概括，分析所学的内容，掌握各章之间的联系。这个总结很重要，是对全课程核心内容、重要理论与方法的综合整理。在总结的基础上，自己对全书内容要有更深一层的了解，要对一些稍有难度的题加以分析解决以检验自己对全部内容的掌握。

  若能把握住以上四个环节，真正做到认真学习，不放过一个疑难点，一定会学好数学。

  当然，对于自考的高等数学一和高等数学二来说，详细具体的计划是必要的（最好计划要有些富余，以减少突发事件对计划的影响），毕竟我们要工作的，时间有限，合理的规划往往会事半功倍，“凡事预则立，不预则废”；历年考题的详细研究也是保证通过的一个不错的途径。因为自考的定位，就是考些我们应知应会的东东，题目往往不会太难，据说题库的总量好像也不大，每年重复出题的几率很高。当然，也会有个别题目有难度，因为被大多数学生考满分，说明老师水平有问题，：），至少试题有问题。


  最后送两句话给自考的朋友，来点私心，也copy一份留送给自己。
  “顽强的毅力可以征服世界上任何一座高峰。”——狄更斯

  “没有比人更高的山，没有比脚更长的路。”――汪国真


  4月17日，我在上海财大考了自考的高数（二），考试比预想中的要顺利很多，估计能够打破我参加自考以来的得分记录。自考不在于分数高低，关键在于花费最少的时间得到你想要的结果，考后回忆自己最后这一个月的复习历程感慨甚多，觉得有必要把自己的考试经历及最后1个月的应试方法写出来和大家共享。
  第一次报名自考的时候就报了高数（二），报名之前就知道高数难，难到很多人为此放弃自考，但我当时并没有把这当一回事，我想我读书的时候成绩最好的就是数学，其他没有把握这门应该没有问题。但真正进行起来我发现完全不是这么回事，要把这两本书完全看懂几乎是不可能完成的任务，线性代数的书看了一半我就放弃了。
  之后的几次自考我都没有报高数（二），一方面是想先把其他科目解决掉，另一方面是对这门课有点畏惧。但再怕还是要考的，我已经上了自考的贼船了！2005年4月的考试我再次报名高数（二），这次我准备了不少资料，最重要的是中华会计网校2004年的语音视频课件及讲义，我下定决心一定要考过。
  我给自己订了个计划，分3个阶段学习高数，先听课件看讲义（从2004年12月到2005年2月，3个月完成60个课件），再做章节练习（2005年3月），最后做模拟试题冲刺复习。计划订得很好，但由于种种原因没有好好执行，想想我真可以算得上“三天打鱼，七天晒网”到了考试前1个月，也就是3月18日才看完线性代数1-4章，概率统计还没有碰（60个课件才完成了25个），而且效果极差。后面课程中涉及到的前面章节的知识点我象没有学过一样，战线拖得太长的弊端暴露无疑。眼见这次考试又要失败，我猛然觉醒，改变了学习方法，在1个月左右的时间里顺利完成了复习。

  最大的改变就是从原先的想法“把书上的知识点弄懂”变成“如何通过这门考核”。
  高数（二）的教材并不适合自学，编排体系比较乱，知识点很多，但真正要求重点把握的知识点有限。概率统计中有3章（1、7、9）几乎是不考的，还有些章节中部分内容考核中也不做要求（如线性代数中的分块矩阵、子空间、约当、惯性，概率统计中的多维随机变量、大数定律和中心极限定律不考，第8章只考一元线性回归方程）。我意识到在不到一个月的时间里完成自考的高数（二）必须从考核重点出发，明确学习重点，对重点逐一落实。自考的考生还是上辅导班比较好，但前提是要碰到一个有应试意识的老师。
  明确了方向以后要做的事情就是如何明确重点。高数使用的是题库，我收集了从2000年到2004年的16份试卷，对主观题的考点做了统计归纳，具体如下：
  线性代数部分：
  矩阵的性质、定义
  29

  方程组求解
  15

  线性关系
  11

  行列式计算
  4

  向量正交
  2

  特征值、特征向量、对角阵、二次型
  11

  概率统计部分：
  概率计算
  23

  分布函数与密度函数
  25

  矩估计
  3

  无偏估计
  11

  极大似然估计
  2

  数学期望
  9

  置信区间
  7

  假设检验
  7

  回归方程
  9

  （以上统计归纳仅供大家参考）

  重点明晰以后我把有限的不到一个月时间重新排了个计划，还是3个阶段。
  一、章节复习，重点归纳
  重点复习历年试卷中重点考核的知识点，对重点题型认真理解，边学习边对知识点总结归纳，把基本的定义、定理、公式，自己掌握较差的知识点以及常见题型的解题思路及解题步骤记录下来，陆陆续续地在一本笔记本上记了40多页（个人认为这个笔记在应试方面的价值高于任何一本参考书）。每一章的总结完成以后再把历年16份试卷中涉及到该章的题目认认真真地做一遍，对基本的题型做到熟练掌握。
  二、各章知识点串联
  各章复习完成以后要把相关的章节串起来，我这时的复习重点是我自己的笔记，书已经被我扔到一边去了。
  三、综合题复习
  最后是看模拟题，这时我已经不动笔做题目了。最后2天是看我买的北大燕园的10套模拟试题，想解题思路（重点是证明题），再对照答案找感觉。当然进考场之前对一些公式之类的还是要再记忆一下。

  最后一个月的复习是相当艰苦的，有时在写字台前一坐就是2个小时，这也算是对我前期复习拖沓的惩罚吧！如果我能够在考前2个月就开始调整状态、改变方法认真复习的话，那会轻松很多。
  高数是自考中一大难点，很多人在心理上就非常畏惧，就象我这次考试时一个考场25个人只来了7个。高数的确很难，但并非高不可攀，综合我的学习经历，我给准备参加自考高数（二）的网友提供以下建议：
  1、建立应试意识，明确考核重点。
  2、重点内容重点复习，不求全部掌握，但对于历年考核的重点必须搞懂。
  3、学会归纳总结。
  我个人认为只要方法对头，平均每天能够投入2个小时，花上1个半月到2个月就能够消灭自考路上最大的拦路虎。
  以上是我自考高数（二）的经历及个人总结的功利性的应试方法，这种方法对高数复习有效，但还是希望大家慎用。


* 学好高等数学必须做好以下六步，
  这六个步骤是学好高等数学的重要环节。

  一．听课，要注于专心

  认真听课，这是个不言而喻的道理。所以就不多谈了，这里只谈谈记笔记的事。要学好高等数学，一定要学会记笔记。记笔记会使听课更专注，也能帮你有效地进行课外的复习巩固。有些同学不会记笔记，只要是老师所讲，言无轻重、话无巨细，统统照记不误，耳、眼、手忙得不亦乐乎，累得还哪里顾得上同步思考，如果是这个样子，倒还不如不记。课堂笔记没必要追求齐全、讲究系统。只要有选择、有重点地记就可以了，特别要记那些有概括性和技巧性的解题方法，常见的、典型的例题。并且要注意解题方法的积累，特别证明题，因为证明题较抽象，常常感觉无从下手。但是课后复习时，一定要对笔记进行适当的整理补充，这就是一本好笔记。如果能再加上自己的心得体会与点评，那就是笔记的极品了。如果预习得好，那么对哪些该记、哪些可不记，也会更有的放矢。

  二．复习，要做到精心

  在整个学习的过程中，复习是最重要的环节，有专家研究过所谓的“知识遗忘规律”有近快远慢的现象。学得越快越多，忘得也越快越多。所以刚学的东西，一下课就要及时复习，这叫“巩固记忆”；期中考试再复习，这叫“加深记忆”；期末考试系统地总复习，这叫“强化记忆”。我们把“知识遗忘规律”总结为“知识记忆的指数衰减律”。于是得到下面两个公式，第一个公式是，具体地说就是“复习记忆公式”，其中为初始学习量，为时间，正数就是复习记忆系数，为时刻的即时记忆量．那么我们的复习就是在做系数的修正工作，反复的复习可以把系数改变成为一个很小的正数，从而达到最好的记忆效果。在的极端情况下，记忆就会被“锁住”而成为所谓的“永久记忆”。由于我们在复习的同时，或在复习的基础上，还在不间断地学习着新的知识，所以反复的滚动复习所起的效果就是知识的积累。我们可以把这个意思写成第二个公式称为“温故知新公式”或“知识积累公式”。如果你在任何时刻的复习都能够做得如此的精心，那么两年以后的考研复习时，就只要在你的“记忆库”中进行轻松的搜索、回顾就可以了。古代孔圣人曰“学而时习之，不亦说乎！”现代世俗人谓“曲不离口，越唱越灵；拳不离手，越打越精”。

  三．作业，要肯下苦心

  作业是复习的一个组成部分，不做作业的复习是虚空复习，不复习而做的作业是低效作业。看书、看笔记、做作业，当然需要有先、后的次序，但是适当地交替进行会更有实效。如果说做好预习是提高课堂听课效率的充分条件，那么及时完成好作业就是读好高等数学的必要条件。老师所布置的作业是最低量作业要求，如果完成这些作业后还找不到明显的感觉，就应该适当地加大自己的作业量。作业是为自己作的，抄作业实际上被欺骗的是自己。老师批过的作业一定要认真仔细地看，这是对老师辛勤劳动的尊重，更是纠正错误，以免重犯的绝好方法。由于多数作业本是由助教批阅的，或许有批错的地方，另外还可 能有对 老师在作业本上的批语没全搞明白的地方，必须及 时问 老师。

  四 . 答疑，解决问题不过夜学习高等数学过程中，会有各种疑问，思考越深，疑问越多。有疑问是好事，攻克的问题无论大小，积累起来就是“学问”。不思无问，就是瞎混混。到头来且不说一事无成，就是想涉险过关也许没那么侥幸。学习要有愤悱意识，不愤不启、不悱不发，自己发问、自己回答。“冥思苦想”之下的“豁然开朗”，那才真叫是“其乐无穷”。当然这是理想境界，可遇可求而不强求。我们的功课门数很多，而精力很有限，不能只化在高等数学一门功课上。问了自己后，再问同窗学友。互相切磋，集思广益。每个人有不同的亮点，一旦互相发生碰撞，兴许就会产生绚丽的火花，三个“臭皮匠”赛过一个诸葛亮嘛！为学生释疑 解难是 老师的天职，老师安排的答疑值班时间，是你应该充分利用的宝贵资源。只要是教高数的，随便 那个 老师都可以问，答疑时，不要总希望老师把问题的解答向你和盘托出。注意给你以提示，让你自己继续思考的老师绝对是个好老师。如果你认为这样的老师不够热心，那你就错了。这时候反倒需要你要有足够的耐心，认真地按照老师指点，动手预算一下。如果在经过老师点拨后你真的懂了，那当然是最好。否则，没有搞懂就是没有搞懂，不要不好意思多问，不要担心老师会不耐烦。老师一定会给你第二步引导，第三次启发。直到完全弄懂为止。
  五 . 课外阅读，看书有选择
  工科和经济类学生对高等数学的学习要求还是很基本的，个人认为没必要去博览群书、广采泛撷。认真研读两本三本高数的教学辅导书就非常足够了。（ 1 ）教材类的书，没有必要多研究。国内各校教材，虽然各有特色，但依据统一的大纲编写，围绕的重点也完全相同。有些名牌大学教改步子特别大，压缩了大纲内的很多基本东西，编入了许多大纲外的东西，例如微分几何的内容、运筹学的原理、还有数值计算的方法。我们认为根本没有必要读这些书。除了你所在学校的指定教材外，别的教材不要去分析比较了；（ 2 ）教学辅导书要有选择地读，有指导地读。不少高数学习指导书，用了大量的篇幅去讲解所谓的重点、难点，在我看来只是教材简单的重复、罗列；还有一些学习指导书，做了很多所谓知识的图表化、网络化、程序化，有些作者看来编得太简单体现不出他的新意，在我看来编得那么复杂真让人好像感到进入了一个高等数学的迷宫。靠它怎么能学得好高等数学。而学好了本课程，这些简单的“知识图表化、网络化、程序化”完全可以由学生自己动手来编。（ 3 ）各种五花八门的高等数学复习资料与习题集目前是最受欢迎的。但是当大家拿到这一种书时，要请注意若缺少对典型例题的深入剖析，没有足够数量的例题供揣摩，对学生也无多大益处。有人一开学，买书很积极，一大摞一大摞的买，这些人基础可能特别好，精力可能特别充沛，一本接着一本地读。咱们不要去和他们攀比，也跟着去买很多书。读数学书是得边看边仔细思考的，怎能像看小说那样一本接着一本地连着读。有需要才去买，买了就认真看，不要把它作为收藏品。用不着包什么花花绿绿的封皮，把涂塑的封面都翻烂了，才算真有本事。对于工科和经济类学生学高等数学来说，我看只要能“读破两本书”，基本上也就能“知识满肚皮”了。
  六．预习，能充分提高听课效率
  做好预习是学好高等数学课程的一个重要环节。预习能充分提高课堂听课效率、良好的预习习惯能够为提高将来的自学能力打下扎实的基础。学生对学习高等数学的感受是：“上课听得懂，作业做不来”。说到底，还是上课没真懂，而其因素之一可能是没有认真预习。对于预习，大家都觉得特别累，既费时时间，又达不到很好的效果（也就是所谓的“事倍功半”）。这是因为大家对预习的要求没掌握好，把预习当作了自学。实际上预习与自学是两个不同概念。下面就具体谈谈高等数学课程的预习要求。首先预习内容不要太多，根据老师的教学进度表，只要把下一次的教学内容预习一下就行了。太多了理解不了，也难于消化。对于较浅显的内容，预习时可以看得细一点，思考得深一点。通过预习能看懂并理解当然是最好，但是一般说来老师的理解会比你更深刻、更全面。你再在课堂里仔细听听老师的分析、老师的理解，他能帮你产生认识上的一个“叠加”或“倍增”甚至是“飞跃”。


* 高等数学基础
  高等数学（一）是经济类各专科专业必修的公共课。高等数学（工专）、（工本）分别是工科类专科、本科专业必修的公共课。尽管要求不同，但是其内容都包括：函数、极限与连续、导数与微分、中值定理与导数应用、积分、无穷级数、多元函数微积分、微分方程等内容。另外由于工科类专业对数学要求高，所以又增加了些内容，并适当提高了难度。
  　　高等数学所学的内容为一元函数微积分学及多元函数微积分学。这就要求自学者高中阶段数学课程中“函数”、“三角函数”、“反三角函数”这一部分知识学习的要牢固，如果这些预备知识学得不扎实，就势必会影响到求导、积分的计算。除了这些必备的知识外，考生同时也应熟练掌握一些中学阶段学过的公式和方法：如：因式分解公式、分式的通分与化简、一元二次方程的解法、三角函数公式、倍角公式等。考生在学习本课程前，如这些预备知识不够的话，建议考生先补习这部分内容，然后再继续高等数学的学习。作为高等数学最重要的公式是导数公式和基本积分公式，这两类公式必须熟记，并能灵活运用。建议自学者在学习此课程的积分部分时，要多多做题，因为很多积分式是不好“积”出来的，必须进行变换，要充分利用各种计算方法和技巧才能继续做下去。另外考生在学习过程中，必须细心，如在求解不定积分时，因缺少常数C而被扣分，是很可惜的。 


* 高数对于自学考试的人来说，十分之难。
  本人从事过多年高数自学考试教学工作，对此深有体会。很多参加自学考试的人都是业余学习，需要很强的毅力。自学考试大部分科目都是考前背一背就可以通过，但高数就完全不同了，它需要扎实的功底，需要很强的逻辑推理能力，需要做大量枯燥无味的习题，需要翻烂一本书的耐力，需要........
  ??所以很多自学考试的“勇士”往往是“栽”在高数这一门上，屡战屡败，盲然中他们付出了太多，失去了太多！我有个学生，高数考了不下十次，其它科目全过了，就等高数一门就可拿到学位了，好惨！
  ??其实高数并非想象的那么不可高攀，最关键的是要注意学习方法，而高数一和高数二的学习又有所不同，下面具体介绍我的对学习高数的技巧。
  ??一）高数一（或工专），首先要有扎实的基本功因为高数一主要是微积分，它实际是有关函数的各种运算。所以首先就是熟悉各种函数的性质、运算等，这些内容都是高中课本上的内容，在高数一书本上只是简单介绍而已。那么对那些准备学习高数一的朋友，要先看看你的基础如何，如果中学的知识全还给老师的话，我建议你先看看中学的书，特别是有关指数函数、幂函数、对数函数、三角函数等一定要很熟，否则要想学好
  高数可能就需要很多时间了。
  ??在有较扎实的基础后，现在可以开始学习高数了。因为高数一各章是相互关联层层推进的，每一章都是后一章的基础，所以学习时一定要按部就班，只有将这一章真正搞懂了才可进入下一章学习，切忌为求快而去速学，欲速则不达嘛，特别是当前面没学好硬去学后面的，会将不懂的问题越集越多，此时自学者的心态就会越来越烦躁，并且不知从何处下手去改善，所见的题目、知识全都不懂，这时很大部分朋友可能就会放弃做逃兵。所以一定要一章一章去学。
  ??在学每一章时，建议先将课本内容看一遍，如果一遍还不明的话，再看一遍。然后看书上的例题，同时试着去做书后的习题。有条件的话，可以买一些参考书来看和做题。做了部分题后，就拿一套以往考试题看看考题中本章有没有题，可以看看关于本章出题的方式。一定要多做题，高数一讲究“熟能生巧”，“熟做高数三千题，考试一定就能行）?
  ??高数一学习是一个长期的过程，所以往后学的过程中，一定要制定计划定期拿一些前面章节的题来做。很多考生在学习过程中，往往学到后面的就把前面内容忘记了。边学边忘肯定是不行的，也会影响到后面的学习。
  ??高数一历年来都是通过率较低的一门学科，原因在于学习着必须真正认真去学才能通过，仅仅靠蒙是很难过的。它出题千变万化，根本无法去估题。并且由于各章相互联系，所以根本无法区分重点和非重点，很多学友问可否划划重点，我的答案是没有重点，因为全是重点。另外强烈推荐学习者去参加一些培训或有一个可以请教的高手，这样可以在遇到难题时及时得到解决同时可以学到各种解题方法(一般书上的解题方法太少)。
  ??另外还要特别强调的是高数学习最好是一个连贯的过程，也就是说一定要制订一个阶段性的学习计划，比如用半年或一年的时间去学它。很多学高数屡战屡败的朋友可能都有这样的经历：准备考比如十月的高数，那么就去报班读，但读到一小半时可能由于种种原因就读不下去了，高数也只学到积分那章就放弃了，心里可能想，哎高数那么难，留到明年再考吧。借口一有，马上放弃十月的考试了。那等明年，这种情况可能又会重复一次，从而周而复始，于是所有科目都过了，只剩下高数这个硬骨头，心理自然就生出高数好难的念头。这种情况在我以前上课时经常发生，刚开课时，教室挤满人，但课程还没上到一半人就走掉一半了，最后能坚持下来的人寥寥无几，而最后能通过考试的恰好就是这些坚持下来的学生。所以有时我就学员当准备考高数时，最好只报考高数一门，全心投入去学习它，当你中途感到吃力坚持不下时，不要找任何借口逃脱，而要想想问题出在哪里，为什么学不下去？找到问题所在然后克服它，那最后一定能成功！
  ??二)高数二的学习与高数一相比有很大的差异。首先说一说它们之间的异同，第一点，高数二不需要太多的基础知识，只是概率里有一点积分和导数的简单计算；第二点，高数一整个内容由微分扣积分这条线贯穿始终，而高数二内容连贯性不是很强；第三点，高数一学习要从根本上加强对基本概念和理论的理解，拓宽解题思路，加强例题典型题的分析和综合练习，并能对典型题举一反三，所以需要做大量题，而高数二要加强基本概念的理解，并能掌握书本上的基本例题即可，不需举一反三，考试题目特别是概率的大题大多千篇一律，无非就是将书上例题数字改一改而已，所以不需做大量题，只需将书上题目“真正”会做即可，如果你能找到大量的题的话，你仔细看看，肯定是千篇一律的。
  ??根据以上几点，我们再来谈谈高数二的学习，首先学习过程中，一定要将每一章内容、概念、定理等真正理解，这可以通过多看几遍书来达到。看书时一定要静下心来，因为高数二内容较难理解，当看不下去时一定不要放弃，要硬着头皮往下读。这里要注意一点的是，高数二中可能会有很多对定理、推论的证明过程，这些证明过程又长又复杂，我建议大家对这些证明过程可以不用去看，你只需捉住精华---定理、推论，好好理解它们就可以了。
  ??当看懂一章内容之后，可以将书后的习题拿来做一做，一定要会做，而不是做完就了事。高数二主要的题型无非就是：（１）行列式的计算；（２）矩阵的运算；（３）线性方程组的求解；（４）特征值和特征向量的计算；（５）二次型的化简；（6）概率论中求概率；（7）求分布与求数字特征；（8）数理统计中求点估计，求区间估计与求检验的拒绝域。书上关于这几方面的题目一定要做完并理解怎样做的。
  ??总得说来，高数一内容好象少点，也不难理解，但由于变化多端，且相互联系紧密，故出题多样，且一道题可能涉及到好几章内容，所以更难点。而高数二，内容较多，也很难理解，但出题简单，题目比较单一，并且有可能都见过。对它们的学习，很精辟的一句话：高数一，多做题；高数二，多看书理解！
  ??以上观点为本人学习和教学中的理解，仅供大家参考。对于广大自考者，学习高数一定要结合自己的知识背景和学习特点总结出自己学习高数的方法和技巧。我相信：天道酬勤，只要付出一份辛苦，一定会有一份收获的！努力吧


* 学习高数一（或称工专），
  首先要具备扎实的基本功。因为高数一主要是微积分，它实际是有关函数的各种运算，因此需要学习者熟悉各种函数的性质运算等，这些基本都是高中课本的内容，在高数一的书本上只是简单介绍而已，所以奉劝那些准备学习高数的朋友，如果中学的数学基础不是很好的话，我建议还是先看看中学的课本，特别是有关指数函数、幂函数、对数函数、三角函数等章节一定要熟悉，最好能够将这些基本函数的各种性质.运算总结归纳成一张表格，方便查询和使用，否则要想学好高数可能会耗费很多时间。 在具备一定的基础后，就可以开始学习高数一了。由于高数一各章是相互关联、层层推进的，每一章都是后一章的基础，所以学习时一定要按部就班，只有将一章真正搞懂了才可进入下一章学习，切忌为求快而去速学，否则将不懂的问题越积越多，会导致自学者的心态越来越烦燥，甚至中途放弃。 在学习每一章时，建议先将课本内容看一遍，如果一遍不明白的话，就再看一遍，然后仔细看书上的例题，看例题时要清楚每一道题的解题步骤是怎么得来的，同时试着自己去做书后的练习题。有条件的同学也可以买一些参考书来做。高数一的学习是一个长期的过程，讲究“熟能生巧”，所以一定要制定学习计划，定期做一些前面章节的题。很多朋友可能会去死记硬背数学公式，其实题目做得多了，公式自然应用自如。 另外，高数一历来都是通过率较低的一门学科，因为学习者必须认真去自学才能通过考试，想蒙混过关是很困难的。高数一出题方式千变万化，根本无法进行估题，并且由于各章节相法互联系，所以没办法区分重点和非重点。建议有条件的学习者可以参加一些培训班或找一位高数学得好的朋友，这样就可以在遇到难题时及时得到解决，同时也可以学到各种解题方法。

* 抓住微积分，它是高数的核心，理解好导数和积分的含义。

  题记―――高等数学，是某些自考专业的重要课程。但对于如何通过考试，如何学好这门课程，许多朋友都是百展莫愁，头痛不已。而高数及格率又是所有科目中及格率最低的几门之一，成为许多考生能否顺利完成专业课程的主要障碍。

  数学，是一门深奥而又有趣的课程。如果增加对这门课程的自信心，不要畏惧它，你会很容易接受这门课，你也会发觉其实这门课程并不难，这对于学好数学是一个非常必要的条件。

  培根说，“数学是科学的大门和钥匙。”的确，数学是科学技术的基础。高等数学与应用数学（包括线性代数、概率论与数理统计、复变函数、数学物理方程，等等）是各专业的重要基础理论课。在会计专业里，比如财务成本管理，审计，评估，管理会计，……等等科目里都有高等数学的影子；在经济学领域里，更是如此。无论微观经济还是宏观经济的经典理论里都有高等数学的烙印。大凡经济学大家们，数学功底都极深。比如，约翰·纳什，萨缪尔逊，中国的茅于轼，……都是数学家或者有相当深厚的数学功底。即使是有些敌视数理经济学的张五常，也免不了要创造一个“张式数学”（这是俺给的名字）来加强论文说服力和逻辑性。

  数学学科的特点是高度的抽象理论与严密的逻辑推理，要通过学习数学提高抽象思维能力，逻辑推理能力，数学运算能力以及应用数学解决实际问题的能力。任何一门数学课的内容都是由基本概念(定义)、基本理论(性质与定理)、基本运算(计算)及应用四部分组成，要学好数学就要在这四个部分上认真钻研刻苦努力，多下功夫。

  基本概念要清楚，要读懂，要理解透彻、叙述准确，不能似是而非、一知半解。数学的推理完全靠基本概念，基本概念不清楚，很多内容就学不懂，无法掌握和运用。例如，线性代数中向量组的线性相关性、线性无关性，向量组的秩与极大无关组，矩阵的相似对角形等，初学者往往掌握不深不透，这就要通过复习与作习题的过程中逐步深入、反复思考、彻底读懂。

  基本理论是数学推理论证的核心，是由一些概念、性质与定理组成的，有些定理并不要求每位初学者都会证明，但定理的条件和结论一定要清楚，要熟悉定理并学会使用定理，有些内容是必须牢记的。例如，矩阵的初等变换是线性代数的重要内容之一。求逆方阵、求矩阵的秩，解线性方程组等都离不开矩阵的初等变换，要懂得其中的道理，为什么可以用初等变换解决以上问题，理论依据是什么？是作初等行变换还是列变换。又如，线性方程组解的存在定理及解的结构定理，判断向量组线性相关与线性无关的有关定理，都是必须牢记的。在概率论的学习中，微积分知识对于理解概率统计的理论很重要。

  掌握数学概念和理论并学会运用主要靠作题，在读懂了内容后要作题，而且要作一定数量的题，才能不断加深对内容的理解，提高解题能力，熟才能生巧，捷径是没有的，“不作题等于没学数学”这是大家公认的事实。在解题过程中要不断总结思路和方法，掌握解题规律性，通过作题提高分析问题、解决问题的能力，也就是逐步提高数学素养。我大学时期的数学老师是北大的研究生（当时正准备去美国读数学博士），福建省当年高考的状元，他高考数学是120分（满分），物理99分，……他告诉我学习微积分的经验就是作四万道题，保证微积分通过（包括考研微积分部分）。——作题的重要性可见一般。

  要学好数学就要认真对待学习的各个环节。首先是听课，听课要精神集中，如能预习效果会更好，要抓住教师讲课中对问题的分析，作好笔记，学会自己动手，边听边记，特别要记下没有听懂的部分。第二个环节是复习整理笔记及作题，课下结合教材和笔记进行复习，要对笔记进行整理按自己的思路，整理出这一次课的内容。在复习好并掌握了内容后再作习题，切忌边翻书边看例题，照猫画虎式地完成练习册上的习题，这样做是收不到任何效果的。要用作题来检验自己的学习，是真懂了还是没完全懂。对于没有彻底读懂的地方再反复思考，直到完全读懂。（当然，我不鼓励象我一样，自己一个人看书，最好找一下免费的视频课件，效率会高些）

  接着是阶段总结。每学完一章，自己要作总结。总结包括一章中的基本概念，核心内容；本章解决了什么问题，是怎样解决的；依靠哪些重要理论和结论，解决问题的思路是什么？理出条理，归纳出要点与核心内容以及自己对问题的理解和体会。

  最后是全课程的总结。在考试前要作总结，这个总结将全书内容加以整理概括，分析所学的内容，掌握各章之间的联系。这个总结很重要，是对全课程核心内容、重要理论与方法的综合整理。在总结的基础上，自己对全书内容要有更深一层的了解，要对一些稍有难度的题加以分析解决以检验自己对全部内容的掌握。

  若能把握住以上四个环节，真正做到认真学习，不放过一个疑难点，一定会学好数学。

  当然，对于自考的高等数学一和高等数学二来说，详细具体的计划是必要的（最好计划要有些富余，以减少突发事件对计划的影响），毕竟我们要工作的，时间有限，合理的规划往往会事半功倍，“凡事预则立，不预则废”；历年考题的详细研究也是保证通过的一个不错的途径。因为自考的定位，就是考些我们应知应会的东东，题目往往不会太难，据说题库的总量好像也不大，每年重复出题的几率很高。当然，也会有个别题目有难度，因为被大多数学生考满分，说明老师水平有问题，：），至少试题有问题。

  最后送两句话给自考的朋友，来点私心，也copy一份留送给自己。
  “顽强的毅力可以征服世界上任何一座高峰。”——狄更斯

  “没有比人更高的山，没有比脚更长的路。”――汪国真

  4月17日，我在上海财大考了自考的高数（二），考试比预想中的要顺利很多，估计能够打破我参加自考以来的得分记录。自考不在于分数高低，关键在于花费最少的时间得到你想要的结果，考后回忆自己最后这一个月的复习历程感慨甚多，觉得有必要把自己的考试经历及最后1个月的应试方法写出来和大家共享。
  第一次报名自考的时候就报了高数（二），报名之前就知道高数难，难到很多人为此放弃自考，但我当时并没有把这当一回事，我想我读书的时候成绩最好的就是数学，其他没有把握这门应该没有问题。但真正进行起来我发现完全不是这么回事，要把这两本书完全看懂几乎是不可能完成的任务，线性代数的书看了一半我就放弃了。
  之后的几次自考我都没有报高数（二），一方面是想先把其他科目解决掉，另一方面是对这门课有点畏惧。但再怕还是要考的，我已经上了自考的贼船了！2005年4月的考试我再次报名高数（二），这次我准备了不少资料，最重要的是中华会计网校2004年的语音视频课件及讲义，我下定决心一定要考过。
  我给自己订了个计划，分3个阶段学习高数，先听课件看讲义（从2004年12月到2005年2月，3个月完成60个课件），再做章节练习（2005年3月），最后做模拟试题冲刺复习。计划订得很好，但由于种种原因没有好好执行，想想我真可以算得上“三天打鱼，七天晒网”到了考试前1个月，也就是3月18日才看完线性代数1-4章，概率统计还没有碰（60个课件才完成了25个），而且效果极差。后面课程中涉及到的前面章节的知识点我象没有学过一样，战线拖得太长的弊端暴露无疑。眼见这次考试又要失败，我猛然觉醒，改变了学习方法，在1个月左右的时间里顺利完成了复习。

  最大的改变就是从原先的想法“把书上的知识点弄懂”变成“如何通过这门考核”。
  高数（二）的教材并不适合自学，编排体系比较乱，知识点很多，但真正要求重点把握的知识点有限。概率统计中有3章（1、7、9）几乎是不考的，还有些章节中部分内容考核中也不做要求（如线性代数中的分块矩阵、子空间、约当、惯性，概率统计中的多维随机变量、大数定律和中心极限定律不考，第8章只考一元线性回归方程）。我意识到在不到一个月的时间里完成自考的高数（二）必须从考核重点出发，明确学习重点，对重点逐一落实。自考的考生还是上辅导班比较好，但前提是要碰到一个有应试意识的老师。
  明确了方向以后要做的事情就是如何明确重点。高数使用的是题库，我收集了从2000年到2004年的16份试卷，对主观题的考点做了统计归纳，具体如下：
  线性代数部分：
  矩阵的性质、定义
  29

  方程组求解
  15

  线性关系
  11

  行列式计算
  4

  向量正交
  2

  特征值、特征向量、对角阵、二次型
  11

  概率统计部分：
  概率计算
  23

  分布函数与密度函数
  25

  矩估计
  3

  无偏估计
  11

  极大似然估计
  2

  数学期望
  9

  置信区间
  7

  假设检验
  7

  回归方程
  9

  （以上统计归纳仅供大家参考）

  重点明晰以后我把有限的不到一个月时间重新排了个计划，还是3个阶段。
  一、章节复习，重点归纳
  重点复习历年试卷中重点考核的知识点，对重点题型认真理解，边学习边对知识点总结归纳，把基本的定义、定理、公式，自己掌握较差的知识点以及常见题型的解题思路及解题步骤记录下来，陆陆续续地在一本笔记本上记了40多页（个人认为这个笔记在应试方面的价值高于任何一本参考书）。每一章的总结完成以后再把历年16份试卷中涉及到该章的题目认认真真地做一遍，对基本的题型做到熟练掌握。
  二、各章知识点串联
  各章复习完成以后要把相关的章节串起来，我这时的复习重点是我自己的笔记，书已经被我扔到一边去了。
  三、综合题复习
  最后是看模拟题，这时我已经不动笔做题目了。最后2天是看我买的北大燕园的10套模拟试题，想解题思路（重点是证明题），再对照答案找感觉。当然进考场之前对一些公式之类的还是要再记忆一下。

  最后一个月的复习是相当艰苦的，有时在写字台前一坐就是2个小时，这也算是对我前期复习拖沓的惩罚吧！如果我能够在考前2个月就开始调整状态、改变方法认真复习的话，那会轻松很多。
  高数是自考中一大难点，很多人在心理上就非常畏惧，就象我这次考试时一个考场25个人只来了7个。高数的确很难，但并非高不可攀，综合我的学习经历，我给准备参加自考高数（二）的网友提供以下建议：
  1、建立应试意识，明确考核重点。
  2、重点内容重点复习，不求全部掌握，但对于历年考核的重点必须搞懂。
  3、学会归纳总结。
  我个人认为只要方法对头，平均每天能够投入2个小时，花上1个半月到2个月就能够消灭自考路上最大的拦路虎。
  以上是我自考高数（二）的经历及个人总结的功利性的应试方法，这种方法对高数复习有效，但还是希望大家慎用。 

* 首先要培养兴趣,
  平时多看点数学方面的书籍,不管是参考书还是科技杂志,其次就是要多做些题,能力是练出来的,不是想出来的,多做一些题你就会慢慢喜欢上数学了,还有课堂上要多做一些笔记,不管书上有没有,经过你的手之后你就会加深印象,对知识也会记忆得更加牢固,也会防止你走神,你不喜欢数学,上课容易走神,多做一下笔记肯定对你有帮助,不仅仅是数学,其他科目也是一样.最后,也是最重要的,就是你要对自己要有信心,不要害怕,相信自己一定能行,如果你连自己都不相信,还谈没学好数学?
  这些都是我的经验所得,今天终于有机会总结出来,希望我的体会能给你带来最大帮助!!!

  补充：

  任何一门数学课的内容都是由基本概念(定义)、基本理论(性质与定理)、基本运算(计算)及应用四部分组成，要学好数学就要在这四个部分上认真钻研刻苦努力，多下功夫。

  1
  基本概念要清楚，要读懂，要理解透彻、叙述准确，不能似是而非、一知半解。

  2

  基本理论是数学推理论证的核心，是由一些概念、性质与定理组成的，有些定理并不要求每位初学者都会证明，但定理的条件和结论一定要清楚，要熟悉定理并学会使用定理，有些内容是必须牢记的。例如，矩阵的初等变换是线性代数的重要内容之一。求逆方阵、求矩阵的秩，解线性方程组等都离不开矩阵的初等变换，要懂得其中的道理，为什么可以用初等变换解决以上问题，理论依据是什么？是作初等行变换还是列变换。又如，线性方程组解的存在定理及解的结构定理，判断向量组线性相关与线性无关的有关定理，都是必须牢记的。在概率论的学习中，微积分知识对于理解概率统计的理论很重要。

  3

  掌握数学概念和理论并学会运用主要靠作题，在读懂了内容后要作题，而且要作一定数量的题，才能不断加深对内容的理解，提高解题能力，熟才能生巧，捷径是没有的，“不作题等于没学数学”这是大家公认的事实。在解题过程中要不断总结思路和方法，掌握解题规律性，通过作题提高分析问题、解决问题的能力，也就是逐步提高数学素养。我大学时期的数学老师是北大的研究生（当时正准备去美国读数学博士），福建省当年高考的状元，他高考数学是120分（满分），物理99分，……他告诉我学习微积分的经验就是作四万道题，保证微积分通过（包括考研微积分部分）。——作题的重要性可见一般。
  4

  要学好数学就要认真对待学习的各个环节。首先是听课，听课要精神集中，如能预习效果会更好，要抓住教师讲课中对问题的分析，作好笔记，学会自己动手，边听边记，特别要记下没有听懂的部分。第二个环节是复习整理笔记及作题，课下结合教材和笔记进行复习，要对笔记进行整理按自己的思路，整理出这一次课的内容。在复习好并掌握了内容后再作习题，切忌边翻书边看例题，照猫画虎式地完成练习册上的习题，这样做是收不到任何效果的。要用作题来检验自己的学习，是真懂了还是没完全懂。对于没有彻底读懂的地方再反复思考，直到完全读懂。（当然，我不鼓励象我一样，自己一个人看书，最好找一下免费的视频课件，效率会高些）

  接着是阶段总结。每学完一章，自己要作总结。总结包括一章中的基本概念，核心内容；本章解决了什么问题，是怎样解决的；依靠哪些重要理论和结论，解决问题的思路是什么？理出条理，归纳出要点与核心内容以及自己对问题的理解和体会。

  最后是全课程的总结。在考试前要作总结，这个总结将全书内容加以整理概括，分析所学的内容，掌握各章之间的联系。这个总结很重要，是对全课程核心内容、重要理论与方法的综合整理。在总结的基础上，自己对全书内容要有更深一层的了解，要对一些稍有难度的题加以分析解决以检验自己对全部内容的掌握。

  若能把握住以上四个环节，真正做到认真学习，不放过一个疑难点，一定会学好数学。



* 数学的考察主要还是基础知识，
  难题也不过是在简单题的基础上加以综合。所以课本上的内容是很重要的，如果课本上的知识都不能掌握，就没有触类旁通的资本。
  　　对课本上的内容，上课之前最好能够首先预习一下，否则上课时有一个知识点没有跟上老师的步骤，下面的就不知所以然了，如此恶性循环，就会开始厌烦数学，对学习来说兴趣是很重要的。课后针对性的练习题一定要认真做，不能偷懒，也可以在课后复习时把课堂例题反复演算几遍，毕竟上课的时候，是老师在进行题目的演算和讲解，学生在听，这是一个比较机械、比较被动的接受知识的过程。也许你认为自己在课堂上听懂了，但实际上你对于解题方法的理解还没有达到一个比较深入的程度，并且非常容易忽视一些真正的解题过程中必定遇到的难点。“好脑子不如赖笔头”。对于数理化题目的解法，光靠脑子里的大致想法是不够的，一定要经过周密的笔头计算才能够发现其中的难点并且掌握化解方法，最终得到正确的计算结果。
  　　其次是要善于总结归类，寻找不同的题型、不同的知识点之间的共性和联系，把学过的知识系统化。举个具体的例子：高一代数的函数部分，我们学习了指数函数、对数函数、幂函数、三角函数等好几种不同类型的函数。但是把它们对比着总结一下，你就会发现无论哪种函数，我们需要掌握的都是它的表达式、图象形状、奇偶性、增减性和对称性。那么你可以将这些函数的上述内容制作在一张大表格中，对比着进行理解和记忆。在解题时注意函数表达式与图形结合使用，必定会收到好得多的效果。
  　　最后就是要加强课后练习，除了作业之外，找一本好的参考书，尽量多做一下书上的练习题（尤其是综合题和应用题）。熟能生巧，这样才能巩固课堂学习的效果，使你的解题速度越来越快

* 如何学好高数

  高等数学是大学新生普遍反映较难的一门课程。大学数学与高中相比逻辑性强，较抽象。再加上合堂较大，进度较快，老师很难个别辅导，很多大学生在开始接触高等数学课时常常会感觉有些茫然。针对这一点，谈一下我的看法。
  学好高等数学必须做好以下六步，这六个步骤是学好高等数学的重要环节。
  一．听课，要注于专心
  认真听课，这是个不言而喻的道理。所以就不多谈了，这里只谈谈记笔记的事。要学好高等数学，一定要学会记笔记。记笔记会使听课更专注，也能帮你有效地进行课外的复习巩固。有些同学不会记笔记，只要是老师所讲，言无轻重、话无巨细，统统照记不误，耳、眼、手忙得不亦乐乎，累得还哪里顾得上同步思考，如果是这个样子，倒还不如不记。
  课堂笔记没必要追求齐全、讲究系统。只要有选择、有重点地记就可以了，特别要记那些有概括性和技巧性的解题方法，常见的、典型的例题。并且要注意解题方法的积累，特别证明题，因为证明题较抽象，常常感觉无从下手。但是课后复习时，一定要对笔记进行适当的整理补充，这就是一本好笔记。如果能再加上自己的心得体会与点评，那就是笔记的极品了。如果预习得好，那么对哪些该记、哪些可不记，也会更有的放矢。
  二．复习，要做到精心 
  在整个学习的过程中，复习是最重要的环节，有专家研究过所谓的“知识遗忘规律”有近快远慢的现象。学得越快越多，忘得也越快越多。所以刚学的东西，一下课就要及时复习，这叫“巩固记忆”；期中考试再复习，这叫“加深记忆”；期末考试系统地总复习，这叫“强化记忆”。我们把“知识遗忘规律”总结为“知识记忆的指数衰减律”。于是得到下面两个公式，第一个公式是 具体地说就是“复习记忆公式”，其中 为初始学习量， 为时间，正数 就是复习记忆体系， 为时刻 的即时记忆量．那么我们的复习就是在做系数 的修正工作，反复的复习可以把系数 改变成为一个很小的正数，从而达到最好的记忆效果。在 的极端情况下，记忆就会被“锁住”而成为所谓的“永久记忆”。由于我们在复习的同时，或在复习的基础上，还在不间断地学习着新的知识，所以反复的滚动复习所起的效果就是知识的积累。我们可以把这个意思写成第二个公式为“温故知新公式”或“知识积累公式”。如果你在任何时刻的复习都能够做得如此的精心，那么两年以后的考研复习时，就只要在你的“记忆库”中进行轻松的搜索、回顾就可以了。古代孔圣人曰“学而时习之，不亦说乎！” 现代世俗人谓“曲不离口，越唱越灵；拳不离手，越打越精”。
  三．作业，要肯下苦心
  作业是复习的一个组成部分，不做作业的复习是虚空复习，不复习而做的作业是低效作业。看书、看笔记、做作业，当然需要有先、后的次序，但是适当地交替进行会更有实效。如果说做好预习是提高课堂听课效率的充分条件，那么及时完成好作业就是读好高等数学的必要条件。老师所布置的作业是最低量作业要求，如果完成这些作业后还找不到明显的感觉，就应该适当地加大自己的作业量。作业是为自己作的，抄作业实际上被欺骗的是自己。师批过的作业一定要认真仔细地看，这是对老师辛勤劳动的尊重，更是纠正错误，以免重犯的绝好方法。由于多数作业本是由助教批阅的，或许有批错的地方，另外还可能有对老师在作业本上的批语没全搞明白的地方，必须及时问老师。 
  四.答疑，解决问题不过夜 
  学习高等数学过程中，会有各种疑问，思考越深，疑问越多。有疑问是好事，攻克的问题无论大小，积累起来就是“学问”。不思无问，就是瞎混混。到头来且不说一事无成，就是想涉险过关也许没那么侥幸。学习要有愤悱意识，不愤不启、不悱不发，自己发问、自己回答。“冥思苦想”之下的“豁然开朗”，那才真叫是“其乐无穷”。当然这是理想境界，可遇可求而不强求。我们的功课门数很多，而精力很有限，不能只化在高等数学一门功课上。问了自己后，再问同窗学友。互相切磋，集思广益。每个人有不同的亮点，一旦互相发生碰撞，兴许就会产生绚丽的火花，三个“臭皮匠”赛过一个诸葛亮嘛！ 为学生释疑解难是老师的天职，老师安排的答疑值班时间，是你应该充分利用的宝贵资源。只要是教高数的，随便那个老师都可以问，答疑时，不要总希望老师把问题的解答向你和盘托出。注意给你以提示，让你自己继续思考的老师绝对是个好老师。如果你认为这样的老师不够热心，那你就错了。这时候反倒需要你要有足够的耐心，认真地按照老师指点，动手预算一下。如果在经过老师点拨后你真的懂了，那当然是最好。否则，没有搞懂就是没有搞懂，不要不好意思多问，不要担心老师会不耐烦。老师一定会给你第二步引导，第三次启发。直到完全弄懂为止。 
  五.课外阅读，看书有选择 
  工科和经济类学生对高等数学的学习要求还是很基本的，个人认为没必要去博览群书、广采泛撷。认真研读两本三本高数的教学辅导书就非常足够了。（1）教材类的书，没有必要多研究。国内各校教材，虽然各有特色，但依据统一的大纲编写，围绕的重点也完全相同。有些名牌大学教改步子特别大，压缩了大纲内的很多基本东西，编入了许多大纲外的东西，例如微分几何的内容、运筹学的原理、还有数值计算的方法。我们认为根本没有必要读这些书。除了你所在学校的指定教材外，别的教材不要去分析比较了；（2）教学辅导书要有选择地读，有指导地读。不少高数学习指导书，用了大量的篇幅去讲解所谓的重点、难点，在我看来只是教材简单的重复、罗列；还有一些学习指导书，做了很多所谓知识的图表化、网络化、程序化，有些作者看来编得太简单体现不出他的新意，在我看来编得那么复杂真让人好像感到进入了一个高等数学的迷宫。靠它怎么能学得好高等数学。而学好了本课程，这些简单的“知识图表化、网络化、程序化”完全可以由学生自己动手来编。（3）各种五花八门的高等数学复习资料与习题集目前是最受欢迎的。但是当大家拿到这一种书时，要请注意若缺少对典型例题的深入剖析，没有足够数量的例题供揣摩，对学生也无多大益处。有人一开学，买书很积极，一大摞一大摞的买，这些人基础可能特别好，精力可能特别充沛，一本接着一本地读。咱们不要去和他们攀比，也跟着去买很多书。读数学书是得边看边仔细思考的，怎能像看小说那样一本接着一本地连着读。有需要才去买，买了就认真看，不要把它作为收藏品。用不着包什么花花绿绿的封皮，把涂塑的封面都翻烂了，才算真有本事。对于工科和经济类学生学高等数学来说，我看只要能“读破两本书”，基本上也就能“知识满肚皮”了。 
  六．预习，能充分提高听课效率 
  做好预习是学好高等数学课程的一个重要环节。预习能充分提高课堂听课效率、良好的预习习惯能够为提高将来的自学能力打下扎实的基础。学生对学习高等数学的感受是：“上课听得懂，作业做不来”。说到底，还是上课没真懂，而其因素之一可能是没有认真预习。对于预习，大家都觉得特别累，既费时时间，又达不到很好的效果（也就是所谓的“事倍功半”）。这是因为大家对预习的要求没掌握好，把预习当作了自学。实际上预习与自学是两个不同概念。
  下面就具体谈谈高等数学课程的预习要求。首先预习内容不要太多，根据老师的教学进度表，只要把下一次的教学内容预习一下就行了。太多了理解不了，也难于消化。对于较浅显的内容，预习时可以看得细一点，思考得深一点。通过预习能看懂并理解当然是最好，但是一般说来老师的理解会比你更深刻、更全面。你再在课堂里仔细听听老师的分析、老师的理解，他能帮你产生认识上的一个“叠加”或“倍增”甚至是“飞跃”。高等数学的不少内容是比较艰深的，对于这些内容你可以看得略微粗一点，思考得浅一点。即便如此，恐怕也要硬着头皮把一个完整的内容看完。预习本来就没有要求你能全部都能搞懂，“模模糊糊、似懂非懂”应该是属于很正常的现象。“似懂”之处，课堂上老师会帮你把模糊的影子变成清晰形象，会使你的认识得到“纠正”、“补充”，变“似懂”为“真懂”；而对于“非懂”之处，在课堂上你一定会听得更认真、更仔细。有些同学觉得高等数学课堂上记笔记抓不住要点。那么请你试试看，加强预习以后，这个感觉会不会得到改善。预习与听课效率之间的关系是不容置疑的，预习后的听课收获与感悟和未经预习的情况不可同日而语。高等数学的教学进度是非常快的，每节课上要学的内容多非常多。如果没有经过预习，要想跟上进度确实不是很容易的。不可否认，也有不少同学觉得不经过预习，高等数学也能学得蛮好。但是我想反问一个问题“如果你预习工作做好了，是不是有可能把高等数学这门课程学得更好呢？” 其实从近期看，预习可以提高听课效率。从远期看，养成良好的预习习惯，可以为将来自我获取新知识（自学）能力打下良好的基础。 
  同学们！高等数学并不可怕，可怕的是你自己没有信心和勇气去学好它。其实，每一门学科都有其固有的规律和结构，以及与这些规律和结构相适应的思想方法，掌握好的学习方法，加上自己刻苦努力，相信你一定能在高等数学的题海中自由徜徉。


* 学好高数的方法
  高数对于自学考试的人来说，十分之难。本人从事过多年高数自学考试教学工作，对此深有体会。很多参加自学考试的人都是业余学习，需要很强的毅力。自学考试大部分科目都是考前背一背就可以通过，但高数就完全不同了，它需要扎实的功底，需要很强的逻辑推理能力，需要做大量枯燥无味的习题，需要翻烂一本书的耐力，需要........ 所以很多自学考试的“勇士”往往是“栽”在高数这一门上，屡战屡败，盲然中他们付出了太多，失去了太多！我有个学生，高数考了不下十次，其它科目全过了，就等高数一门就可拿到学位了，好惨！ 

  　　其实高数并非想象的那么不可高攀，最关键的是要注意学习方法，而高数一和高数二的学习又有所不同，下面具体介绍我的对学习高数的技巧。 

  　　一）高数一（或工专），首先要有扎实的基本功因为高数一主要是微积分，它实际是有关函数的各种运算。所以首先就是熟悉各种函数的性质、运算等，这些内容都是高中课本上的内容，在高数一书本上只是简单介绍而已。那么对那些准备学习高数一的朋友，要先看看你的基础如何，如果中学的知识全还给老师的话，我建议你先看看中学的书，特别是有关指数函数、幂函数、对数函数、三角函数等一定要很熟，否则要想学好高数可能就需要很多时间了。 

  　　在有较扎实的基础后，现在可以开始学习高数了。因为高数一各章是相互关联层层推进的，每一章都是后一章的基础，所以学习时一定要按部就班，只有将这一章真正搞懂了才可进入下一章学习，切忌为求快而去速学，欲速则不达嘛，特别是当前面没学好硬去学后面的，会将不懂的问题越集越多，此时自学者的心态就会越来越烦躁，并且不知从何处下手去改善，所见的题目、知识全都不懂，这时很大部分朋友可能就会放弃做逃兵。所以一定要一章一章去学。 

  　　在学每一章时，建议先将课本内容看一遍，如果一遍还不明的话，再看一遍。然后看书上的例题，同时试着去做书后的习题。有条件的话，可以买一些参考书来看和做题。做了部分题后，就拿一套以往考试题看看考题中本章有没有题，可以看看关于本章出题的方式。一定要多做题，高数一讲究“熟能生巧”，“熟做高数三千题，考试一定就能行）。  

  　　高数一学习是一个长期的过程，所以往后学的过程中，一定要制定计划定期拿一些前面章节的题来做。很多考生在学习过程中，往往学到后面的就把前面内容忘记了。边学边忘肯定是不行的，也会影响到后面的学习。 

  　　高数一历年来都是通过率较低的一门学科，原因在于学习着必须真正认真去学才能通过，仅仅靠蒙是很难过的。它出题千变万化，根本无法去估题。并且由于各章相互联系，所以根本无法区分重点和非重点，很多学友问可否划划重点，我的答案是没有重点，因为全是重点。另外强烈推荐学习者去参加一些培训或有一个可以请教的高手，这样可以在遇到难题时及时得到解决同时可以学到各种解题方法(一般书上的解题方法太少)。 

  　　另外还要特别强调的是高数学习最好是一个连贯的过程，也就是说一定要制订一个阶段性的学习计划，比如用半年或一年的时间去学它。很多学高数屡战屡败的朋友可能都有这样的经历：准备考比如十月的高数，那么就去报班读，但读到一小半时可能由于种种原因就读不下去了，高数也只学到积分那章就放弃了，心里可能想，哎高数那么难，留到明年再考吧。借口一有，马上放弃十月的考试了。那等明年，这种情况可能又会重复一次，从而周而复始，于是所有科目都过了，只剩下高数这个硬骨头，心理自然就生出高数好难的念头。这种情况在我以前上课时经常发生，刚开课时，教室挤满人，但课程还没上到一半人就走掉一半了，最后能坚持下来的人寥寥无几，而最后能通过考试的恰好就是这些坚持下来的学生。所以有时我就学员当准备考高数时，最好只报考高数一门，全心投入去学习它，当你中途感到吃力坚持不下时，不要找任何借口逃脱，而要想想问题出在哪里，为什么学不下去？找到问题所在然后克服它，那最后一定能成功！ 

  　　二)高数二的学习与高数一相比有很大的差异。首先说一说它们之间的异同，第一点，高数二不需要太多的基础知识，只是概率里有一点积分和导数的简单计算；第二点，高数一整个内容由微分扣积分这条线贯穿始终，而高数二内容连贯性不是很强；第三点，高数一学习要从根本上加强对基本概念和理论的理解，拓宽解题思路，加强例题典型题的分析和综合练习，并能对典型题举一反三，所以需要做大量题，而高数二要加强基本概念的理解，并能掌握书本上的基本例题即可，不需举一反三，考试题目特别是概率的大题大多千篇一律，无非就是将书上例题数字改一改而已，所以不需做大量题，只需将书上题目“真正”会做即可，如果你能找到大量的题的话，你仔细看看，肯定是千篇一律的。 

  　　根据以上几点，我们再来谈谈高数二的学习，首先学习过程中，一定要将每一章内容、概念、定理等真正理解，这可以通过多看几遍书来达到。看书时一定要静下心来，因为高数二内容较难理解，当看不下去时一定不要放弃，要硬着头皮往下读。这里要注意一点的是，高数二中可能会有很多对定理、推论的证明过程，这些证明过程又长又复杂，我建议大家对这些证明过程可以不用去看，你只需捉住精华---定理、推论，好好理解它们就可以了。 

  　　当看懂一章内容之后，可以将书后的习题拿来做一做，一定要会做，而不是做完就了事。高数二主要的题型无非就是：（1）行列式的计算；（2）矩阵的运算；（3）线性方程组的求解；（4）特征值和特征向量的计算；（5）二次型的化简；（6）概率论中求概率；（7）求分布与求数字特征；（8）数理统计中求点估计，求区间估计与求检验的拒绝域。书上关于这几方面的题目一定要做完并理解怎样做的。 

  　　总得说来，高数一内容好象少点，也不难理解，但由于变化多端，且相互联系紧密，故出题多样，且一道题可能涉及到好几章内容，所以更难点。而高数二，内容较多，也很难理解，但出题简单，题目比较单一，并且有可能都见过。对它们的学习，很精辟的一句话：高数一，多做题；高数二，多看书理解！ 

  　　以上观点为本人学习和教学中的理解，仅供大家参考。对于广大自考者，学习高数一定要结合自己的知识背景和学习特点总结出自己学习高数的方法和技巧。我相信：天道酬勤，主要付出一份辛苦，一定会有一份收获的！努力吧！


