* Emacs IRC -- Erc
** IRC
   
    加入 channel （房间）
    聊天
    设置自己的 nickname
   
Erc 使用
常用快捷键

各种不同的 IRC 客户端除了一些使用区别，其他功能基本类似。Erc，Xchat， irssi 等基本操作也都建立在对于 IRC 使用方式的基础之上。可能
不同的客户端提供不同的方式执行一些 IRC 命令，但是直接输入对应的 IRC 命令也可以。

IRC

本文示例，默认连接的 IRC 服务器为： irc.freenode.net

** 加入 channel （房间）

当我们连接到一个 IRC 服务器后，就可以使用 "/join" 命令加入感兴趣的房间聊天。

/join #ubuntu-cn
/join #fedora-cn

** 聊天

使用 IRC 不聊天做什么？任何客户端下，只要连接到一个 IRC 服务器（最常用的是 irc.freenode.net），加入 channel （或者称呼为房间），就可
以说话了。

指定用户名发信息

如果信息前想加入某个人的名字，这样能让别人注意到你的信息，却又要大家都能看见。可以先输入该用户名（用 Tab 键补全），再输入信息即可
：

<Jian> jianlee: 这是一条测试信息。

私聊

为了不打扰大家，私聊是一种礼貌。

使用 "/msg 用户名"

/msg nickname "信息"

这样就可以和 nickname 私聊了。

使用 "/query 用户名"

如果要和 "Jian" 私聊，可以这样

/query Jian

** 设置自己的 nickname

注册 nickname

我们自己使用的 nickname 总是不希望别人用吧？注册一下！以链接 irc.freenode.net 为例。无论是什么客户端，都会需要我们填写一个
nickname，我开始用 "Jian" 登录上去后，系统显示：

-NickServ- Jian is not a registered nickname.

提示我 "Jian" 是一个未注册的 nickname。现在可以使用 "/msg NickServ" 命令注册我的 nickname。网上的一些帖子可能比较老，可以看看 
http://freenode.net/faq.shtml#nicksetup 。不过还是以你系统上 IRC 帮助为准，输入 "/msg NickServ help" 可以得到帮助。

通过帮助我们能看到使用 "REGISTER" 命令可以注册 nickname，根据帮助我们还可以看到用 "/msg NickServ help REGISTER" 命令就能得到
"REGISTER" 的具体使用帮助。

现在我们知道要注册当前使用的 nickname — "Jian" ，需要这样：

/msg NickServ REGISTER 密码 邮箱

这样就把 "Jian" 注册上了，还设置了密码和邮箱，这时候邮箱会收到一封确认邮件，照着邮件做就可以了。

修改 nickname 的属性值

我们已经注册好了 "Jian"，可是现在又想修改 "Jian" 的密码怎么办？可以使用 "/msg NickServ help SET" 得到 "SET" 命令帮助，修改密码可以
这样：

/msg NickServ SET PASSWORD 新密码

其他如修改 EMAIL，隐藏资料等都可以用 "SET" 命令。

** 基本的IRC命令

命令列表

+------------------------------------------------------------------------------------------------------+
| /msg nickserv help               | 注冊 nickname                                                     |
|----------------------------------+-------------------------------------------------------------------|
| /nick 名字                       | 改名字                                                            |
|----------------------------------+-------------------------------------------------------------------|
| /names [频道]                    | 查看当前[频道]所有用户                                            |
|----------------------------------+-------------------------------------------------------------------|
| /whois 名字                      | 常看某人資料                                                      |
|----------------------------------+-------------------------------------------------------------------|
| /whoami                          | 自己                                                              |
|----------------------------------+-------------------------------------------------------------------|
| /who ip                          | 常看某IP登錄的所有用戶                                            |
|----------------------------------+-------------------------------------------------------------------|
| /Who channel                     | 显示此频道的人                                                    |
|----------------------------------+-------------------------------------------------------------------|
| /Who *                           | 显示参加当前频道的人                                              |
|----------------------------------+-------------------------------------------------------------------|
| /join #房間名                    | 加入這個房間，如果房間不存在，服務器可能會創建這個房間            |
|----------------------------------+-------------------------------------------------------------------|
| /part #房間名原因                | 離開房間，并留下原因                                              |
|----------------------------------+-------------------------------------------------------------------|
| /quit 退出的原因                 | 退出服務器，并留下原因                                            |
|----------------------------------+-------------------------------------------------------------------|
| /away 原因                       | 暫時離開，并留下原因                                              |
|----------------------------------+-------------------------------------------------------------------|
| /invite 昵稱 #房間名             | 邀請某人到指定房間                                                |
|----------------------------------+-------------------------------------------------------------------|
| /kick #房間名昵稱原因            | 剔出某人，附上原因，需要權限                                      |
|----------------------------------+-------------------------------------------------------------------|
| /topic #房間名' 房間主題         | 如果你是房間主持人，可以改變房間的主題                            |
|----------------------------------+-------------------------------------------------------------------|
| /me 您要作的動作                 | 向当前聊天室中发送一个动作 (动作使用第三人称陈述，例如 /me jumps) |
|----------------------------------+-------------------------------------------------------------------|
| /msg 昵稱(或#房間) 有要說的話    | 向某人發信息                                                      |
|----------------------------------+-------------------------------------------------------------------|
| /query 昵稱要說的話              | 私聊                                                              |
|----------------------------------+-------------------------------------------------------------------|
| /notice 昵稱(或#房間名) 要說的話 |                                                                   |
|----------------------------------+-------------------------------------------------------------------|
| /list                            | 查看服務器上所有房間及主題                                        |
|----------------------------------+-------------------------------------------------------------------|
| /list #ubuntu-cn                 | 列出這個房間                                                      |
|----------------------------------+-------------------------------------------------------------------|
| /list -MIN a -MAX b              | 查看人數大于a小于b的房間                                          |
|----------------------------------+-------------------------------------------------------------------|
| /list * abc *                    | 所有行abc字符串的房間                                             |
|----------------------------------+-------------------------------------------------------------------|
| /flush                           | 终止当前命令的输出操作                                            |
|----------------------------------+-------------------------------------------------------------------|
| /help                            | 显示所有IRC命令                                                   |
|----------------------------------+-------------------------------------------------------------------|
| /join                            | 加入/建立聊天室                                                   |
|----------------------------------+-------------------------------------------------------------------|
| /leave channel                   | 离开某一频道                                                      |
|----------------------------------+-------------------------------------------------------------------|
| /mode +(-)i                      | 锁住聊天室                                                        |
|----------------------------------+-------------------------------------------------------------------|
| /mode +(-)o                      | 设定管理员权限                                                    |
|----------------------------------+-------------------------------------------------------------------|
| /knock                           | 要求进入私人聊天室                                                |
|----------------------------------+-------------------------------------------------------------------|
| /invite                          | 邀请用户进入私人聊天室                                            |
|----------------------------------+-------------------------------------------------------------------|
| /privmsg                         | 悄悄话                                                            |
|----------------------------------+-------------------------------------------------------------------|
| /ignore                          | 忽略                                                              |
|----------------------------------+-------------------------------------------------------------------|
| /topic                           | 更换聊天室主题                                                    |
|----------------------------------+-------------------------------------------------------------------|
| /kick                            | 把用户踢出聊天室                                                  |
|----------------------------------+-------------------------------------------------------------------|
| /quit                            | 退出聊天室                                                        |
+------------------------------------------------------------------------------------------------------+
</example>

** 常用命令详解

所有的IRC命令都是由“/”引导。在不引起混淆的情况下，IRC命令允许简写。例如，/join 命令可以简写为/j，/jo或者/joi。

/nick

更改昵称的基本方法是："/n(ick) 新昵称"

您的昵称可以包含英文字母，数字，汉字及下划线等。但是，昵称不能超过50个（每个字符和汉字都算一个字），而且不能包含$，+，！和空格。

/join

/join命令的格式是："/j(oin) 聊天室名"

如果聊天室已经存在，您就进入该聊天室。此时，/join 命令等价于聊天室列表工具按钮中的“进入”。

如果聊天室不存在，您就建立了一个新的聊天室并进入。此时，/join 命令等价于工具按钮中的“建聊天室”。

聊天室的名字可以包含英文字母，数字，汉字及下划线等。但是，不能超过50个字（每个字符和汉字都算一个字），而且不能包含$，+，！和空格。

/mode

/mode +(-)i

/mode +(-)i 命令可以用来锁住（解锁）用户自建的聊天室（私人聊天室）。其命令格式是: "/m(ode) +i 或 /m(ode) -i"

只有用户自建的聊天室才能加锁。

未经管理员邀请，其他用户不能进入私人聊天室。

/mode +(-)o

/mode +(-)o 命令可以让聊天室管理员赋予或者剥夺其他用户的管理员身份。其命令格式是："/m(ode) +o 昵称或 /m(ode) -o 昵称"

只有聊天室管理员才能使用这个命令。

/knock

/knock 命令可以让您询问私人聊天室管理员是否可以进入该私人聊天室。其命令格式是："/k(nock) 房间名 [消息]"

/invite

/invite 命令可以让聊天室管理员邀请其他用户进入私人聊天室。其命令格式是: "/i(nvite) 昵称"

只有私人聊天室的管理员才能使用这个命令。

** Erc 使用

常用快捷键

快捷键  || 对于 IRC 命令 || 含义
C-c C-n | /names [#fedora-zh] | 列出频道里的用户
C-c C-b | 无，emacs的特性 | 切换频道
C-c C-j | /join #fedora-zh | 加入频道
C-c C-p | /leave [#fedora-zh] | 退出频道

* ERC使用简介

ERC, emacs irc client, 即是 emacs 里登录 irc 的客户端。irc 是什么? internet relay chat, 简单地说，就是用于群聊的。一帮无聊的
geeks 成天没事干，就在上面灌水，所以上面的 channel 技术类的占绝大数，比如 emacs, c++, debian, scheme 等等。

好，开始 ERC 之旅，先让我们登录到 #emacs-cn 上去：

a) M-x erc-select

host: irc.debian.org
port: 6667 到 7000 随便用一个
username: 先随便填一个，比如 foo
password: 还没注册的可以直接回车

b) 这时候你就进入了一个名字类似 “irc.debian.org:6669″ 的 server buffer. 接着执行：

ERC> /join #emacs-cn

就进入 #emacs-cn channel 啦!

c) 如何注册

切换到刚才那个 server buffer, 输入：

ERC> /msg nickserv help register

按着提示一步一步来就行，根据 irc server 的不同，有些会需要你用有效邮箱来确认一下。注册 id 的好处就是，这个 id 就不会被别人抢走了
，比如有人已经用 foo 登录了，但这被你注册了，你连进去的时候，就能把名字抢过来，而对方可能会变成 foo` 之类的别名。

以上其实对于所有 irc client 来讲都是通用的。接下来是我的 ERC 一些配置供参考：

1. 基本设置

编码，尽量 utf-8 (#emacs-cn 也是用 utf-8):

^?View Code LISP

(setq erc-default-coding-system '(utf-8 . utf-8))

如果某个 channel 是别的编码，也可以单独设置，例如国内某个 irc server 上 #linuxfire 就是用 gbk 编码，我们单独为它设置：

^?View Code LISP

(setq erc-encoding-coding-alist '(("#linuxfire" . chinese-iso-8bit))

设置 nick, 全名: nick 就是登录时用的，full name 是别人查询你的时候显示的信息。(类似BBS 的 C-a )

^?View Code LISP

1 (setq erc-nick "xwl"                   
2       erc-user-full-name "William Xu") 

2. 登录后自动加入预定的 channels

^?View Code LISP

1 (erc-autojoin-mode 1)                                       
2 (setq erc-autojoin-channels-alist                           
3       '(("oftc.net"                 ; debian.org 是它的别名 
4          "#debian-zh"                                       
5          "#emacs-cn")))                                     

3. 连接服务器或进入聊天室后自动执行预设操作
ERC 提供各种各样的 hook 让你在某个操作（登入 server, 进入channel等）之后执行一些你预设的操作。比如如果你有某个 channel 的管理员权
限，可以在加入聊天室时自动转换到管理员身份：

^?View Code LISP

1 (defun xwl-erc-auto-op ()                                  
2   (let ((b (buffer-name)))                                 
3     (when (string= b "#emacs-cn")                          
4       (erc-message "PRIVMSG" (concat "chanserv op " b))))) 
5                                                            
6 (add-hook 'erc-join-hook 'xwl-erc-auto-op)                 

4. 过滤信息
如果你对某些消息或者某个人说的话特别感兴趣，我们可以通过关键字匹配对相关信息进行高亮。例如：

^?View Code LISP

1 (erc-match-mode 1)                     
2 (setq erc-keywords '("emms" "python")) 
3 (setq erc-pals '("rms"))               

相反地，如果你对某些消息不感兴趣，比如有人进来啦，有人出去啦，如此这般一下就不会看到了：

^?View Code LISP

1 (setq erc-ignore-list nil)            
2 (setq erc-hide-list                   
3       '("JOIN" "PART" "QUIT" "MODE")) 

5. 新信息提醒

信息一般可分为三种：

1) 某人悄悄跟你说话(即所谓的 private message)，这会打开一个新小窗，即 buffer.

ERC>/msg NICK how are you doing

2) 某人公开地跟你说话，即别的在 channel 里的人也能看到。一般来说，习惯用 nick加 `:’ 表示。(要输入某人 nick 的时候，首字母加 TAB
就能帮你补全，一次不行，多 TAB 几次可以选择)

<xwl> ahei: 你可以 match regexp,

3) 别的情形。

ERC 会通过 erc-modified-channels-object 来设置 mode line，提示有新消息，类似：

[#o: 38, #emacs-cn: 5]

为什么要区分以上三种情形呢? 因为我们可以对不同信息，用不同的颜色在mode line 来提示，这样方便你决定是不是要及时地去查阅这条消息。

ERC 本身只在 mode line 提示新消息，如果你切换到别的程序去了，比如在firefox 里看 ppmm，还想被提醒的话，可以借助一些外部工具来实现
。mac 下用 growl，linux 可以用 zenity，windows 不知有什么类似工具? 给个例子：

^?View Code LISP

1  (defun xwl-erc-text-matched-hook (match-type nickuserhost message)        
2    "Shows a growl notification, when user's nick was mentioned.            
3       If the buffer is currently not visible, makes it sticky."            
4    (when (and (erc-match-current-nick-p nickuserhost message)              
5               (not (string-match (regexp-opt '("Users"                     
6                                                "User"                      
7                                                "topic set by"              
8                                                "Welcome to "               
9                                                "nickname"                  
10                                               "identified"                
11                                               "invalid"                   
12                                               ))                          
13                                 message)))                                
14     (let ((s (concat "ERC: " (buffer-name (current-buffer)))))            
15       (case system-type                                                   
16         ((darwin)                                                         
17          (xwl-growl s message))))))                                       
18                                                                           
19 (add-hook 'erc-text-matched-hook 'xwl-erc-text-matched-hook)              
20                                                                           
21 (defun xwl-growl (title message)                                          
22   (start-process "growl" " growl" growlnotify-command title "-a" "Emacs") 
23   (process-send-string " growl" message)                                  
24   (process-send-string " growl" "\n")                                     
25   (process-send-eof " growl"))                                            

6. 时间戳

^?View Code LISP

(erc-timestamp-mode 1)

下面这个变量可以控制时间戳的显示方式，比如位置什么的，默认值：

^?View Code LISP

(setq erc-insert-timestamp-function 'erc-insert-timestamp-left)

7. log
我们可以将 channel 里的聊天记录都保存下来，方便日后查询，或者有时候你的 emacs 突然挂掉的时候，还能找到挂之间有没有人对你说了什么
。

^?View Code LISP

1  (require 'erc-log)                                 
2  (erc-log-mode 1)                                   
3  (setq erc-log-channels-directory "~/var/erc/"      
4        erc-save-buffer-on-part t                    
5        erc-log-file-coding-system 'utf-8            
6        erc-log-write-after-send t                   
7        erc-log-write-after-insert t)                
8                                                     
9  (unless (file-exists-p erc-log-channels-directory) 
10   (mkdir erc-log-channels-directory t))            

最后，ERC 上 irc 还是蛮舒服的，因为所有的、你熟悉的 emacs 编辑命令都在那里! 国内 irc 用户还是少了点，对岸台湾倒是蛮多的。大家有空
就上来玩吧~ 要是想看我的配置可以在 github.com 上看我的配置文件：
