* 历史人物对于墨家的评价
曹操：
侈恶之大，俭为共德。兼爱尚同，疏者为戚。

孙中山：
古时最讲‘爱’字的莫过于墨子。墨子所讲的‘兼爱’，与耶稣所讲的博爱是一样的。

陈独秀：
假若墨学不绝，汉以来的历史绝不会如此。

毛泽东：
墨子是个劳动者，他不做官，但他是比孔子高明的圣人。

王安石：
墨子之道，摩顶放踵以利天下。

蔡元培：
墨学中断使中国科学不得发达。

章太炎：
墨子之道德，非孔老所敢窥视。

梁启超：
吾尝谛观思惟，则墨学精神，深入人心，至今不附，因以形成吾民族特性之一者，盖有之矣。

王充：
圣贤之业，皆以薄葬省用为务。然而世尚厚葬，有奢泰之失者，儒家论不明，墨家论之非故也。

司马谈：
强本节用，则人给家足之道也。此墨子之所长，虽百家弗能费也。

长孙无忌：
墨者强本节用之术也，上述尧舜禹夏禹之行，茅茨不翦，粝梁之食，铜棺三寸，贵俭兼爱，严父上德，以孝示天下，右鬼神而非命。

鲁胜：
墨子著书作《辩经》以立名本，惠施、公孙龙祖述其学，以正别名显于世。

班固：
墨家者流，盖出于清庙之守。茅屋采椽，是以贵俭；养三老五更，是以兼爱；选士大射，是以上贤；宗祀严父，是以右鬼；顺四时而行，是以非命
；以孝视天下，是以尚同。

刘安：
墨子服役者百八十人，皆可使赴火蹈刀，死不还踵，化之所至也。

陶渊明：
不累于俗，不饰于物，不尊于名，不忮于众，此宋刑、尹文之墨；裘褐为服，日夜不休，是以苦为极者，相里勤、五侯子之墨；俱称而背谲不同，
相谓别墨以坚白，此苦获、已齿、邓陵子之墨。

荀子：
假今之世，饰邪说，交奸言，以枭乱天下，矞宇嵬琐，使天下混然不知是非治乱之所存者……
不知壹天下、建国家之权称，上功用、大俭约而僈差等，曾不足以容辨异、县君臣；然而其持之有故，其言之成理，足以欺惑愚众，是墨翟、宋钘
也。

孟子：
贼道也。
与杨、墨辩者，如追放豚。
杨、墨之道不息，孔子之道不著。是邪说诬民，充塞仁义也。仁义充塞，则率兽食人。
墨氏兼爱，是无父也。无君无父，是禽兽也。


* 墨子名言40句

1.      志不强者智不达，言不信者行不果。

2.      名不可简而成也，誉不可巧（伪诈）而立也。君子以身戴（载）行者也。

3.      仁人之所以为事者，必兴天下之利，除天下之害。

4.      天下之人皆相爱，强不执弱，众不劫寡，富不侮贫，贵不傲贱，诈不欺愚。

5.      染于苍则苍，染于黄则黄。

6.      节俭则昌，淫佚则亡。

7.      有能则举之，无能则下之。

8.      力，形之所以奋也。圆，一中同长也

9.      兴天下之利，除天下之害。

      墨家十论
10.     兼爱。
11.     非攻。
12.     尚贤
13.     尚同。
14.     节用。
15.     节葬。
16.     非乐。
17.     非命。
18.     天志。
19.     明鬼。

20.     兼相爱，交相利。

21.     若使天下兼相爱，爱人若爱其身，犹有不孝者？

22.     今重不为不义攻国。

23.     备者，国之重也。

24.     无不让也，不可，说在殆。

25.     无言而不信，不德而不报，投我以桃，报之以李。

26.     君子不镜于水而镜于人。

27.     万事莫贵于义。

28.     以攻战亡者，可胜数。

29.     名不可简而成也，誉不可巧而立也，君子以身戴行者也。

30.     钓者之恭，非为鱼赐也；饵鼠以虫，非爱之也。

31.     俭节则唱，淫佚则亡。

32.     人不分幼长贵贱，皆天只臣也

33.     “凡入国，必择务而从事焉。国家昏乱，则语之尚贤、尚同；国家贫，则语之节用、节葬；国家熹音湛湎，则语之非乐、非命；
        国家淫僻无礼，则语之尊天、事鬼；国家务夺侵凌，即语之兼爱、非攻。”

34.     三表：“上本之于古者圣王之事”，“下原察百姓耳目之实” ，“废（发）以为刑政，观其中国家百姓人民之利”

35.     “顺天意者”，“必得赏”；“反天意者”，“必得罚”。

36.     快马加鞭
	解：给快跑的马再抽几鞭，使它跑得更快。用来形容：快上加快，疾弛飞奔，或用以比喻不断努力，继续前进。

	述源：《墨子•耕柱》："耕柱子曰：'将驱骥也。'子墨子曰：'何故驱骥也？'耕柱子曰：骥足以责。'子墨子曰：'我亦以子为足以则。'" 
	墨子学生耕柱子，聪颖过人，但不知发奋努力，墨子总是责备他。耕柱子说："先生，我真的没有什么比别人强的地方吗？"墨子说："我将
	要上太行 山，乘坐快马和牛，你打算鞭策哪一个呢？"耕柱子很自信地说："我要鞭策快马。"墨子追问："你为什么要鞭策快马？"耕柱子
	说："快马值得鞭策 。因为它感觉灵敏，鞭打它可以使它跑得更快!"墨子的用意是启发耕柱子，让他努力求学，奋发上进，现已水到渠成，
	就对耕柱子说："我也认为你 是值得鞭策的!你应该象快马一样力求上进啊!"以后耕柱子发奋读书，力求上进，再也不用老师整日督促了。 

37.     若使天下兼相爱，国与国不相攻，家与家不相乱，盗贼无有，君臣父子皆能孝慈，若此，则天下治。故圣人以治天下为事者，恶得不禁恶
	而劝爱？故天下兼相爱则治，交相恶则乱。

38.     天下之人皆不能相爱，强必执弱、富必侮贫、贵必敖贱、诈必欺愚。凡天下祸篡怨恨其所以起者以不相爱生也。

39.     夫爱人者人必从而爱之，利人者人必从而利之，恶人者人必从而恶之，害人者人必从而害之。

40.     无言而不应，无德而不报，投我以桃，报之以李，即此言爱人者必见爱也，而恶人者必见恶也。
