# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1496377054);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1496377174);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1496376934);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1496377294);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("datareporting.sessions.current.activeTicks", 13);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 7006);
user_pref("datareporting.sessions.current.main", 30);
user_pref("datareporting.sessions.current.startTime", "1496376903196");
user_pref("datareporting.sessions.current.totalTime", 947);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 19);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.1.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1496377056);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "52.1.1");
user_pref("extensions.lastPlatformVersion", "52.1.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"messagingmenu@mozilla.com\":{\"d\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"e\":true,\"v\":\"1.3.1\",\"st\":1494431900000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.1.1\",\"st\":1494431948000}}}");
user_pref("idle.lastDailyNotification", 1496377654);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 15);
user_pref("mailnews.database.global.datastore.id", "74c913b3-6ef3-4b53-9711-086a84265e5");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "52.1.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1496377654);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("services.blocklist.addons.checked", 1496362743);
user_pref("services.blocklist.clock_skew_seconds", 14431);
user_pref("services.blocklist.gfx.checked", 1496362743);
user_pref("services.blocklist.last_update_seconds", 1496362743);
user_pref("services.blocklist.plugins.checked", 1496362743);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1496377654);
user_pref("toolkit.telemetry.cachedClientID", "ef2fb456-524c-498b-b606-a66533c5e9b2");
user_pref("toolkit.telemetry.previousBuildID", "20170510141111");
user_pref("toolkit.telemetry.prompted", 2);
